// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbOh8sOXo8oLt55oQ0ypAKvWYPlgHMgoo',
    appId: '1:589840820110:web:b51f04d032508d6ccaa6df',
    messagingSenderId: '589840820110',
    projectId: 'event-hub-368414',
    authDomain: 'event-hub-368414.firebaseapp.com',
    storageBucket: 'event-hub-368414.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUguFzyBP4sQmW7YLdbIJe2ne2SCR2tcg',
    appId: '1:589840820110:android:a4bfc2d2782236c9caa6df',
    messagingSenderId: '589840820110',
    projectId: 'event-hub-368414',
    storageBucket: 'event-hub-368414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL_5RoeqoEDgGY-6Fx_XjHwfkHaL7aSt4',
    appId: '1:589840820110:ios:2f140ccf59a6eb27caa6df',
    messagingSenderId: '589840820110',
    projectId: 'event-hub-368414',
    storageBucket: 'event-hub-368414.appspot.com',
    iosClientId: '589840820110-fpcraquhsgc8hic01er2v82tprkg2pmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventHub',
  );
}
